config:
  aws:region: ap-southeast-1
  environment: dev
  project: aurora-audit-log-backup-lab
  owner: zzhe
  ec2-stress-client:keyPairName: "keypair-root-sin"
  ec2-stress-client:instanceType: "m8g.large"