config:
  aws:region: ap-southeast-1
  environment: dev
  project: aurora-audit-log-backup-lab
  owner: zzhe
  backup-solution:dbScannerMemory: "512"
  backup-solution:dbScannerTimeout: "60"
  backup-solution:logDetectorMemory: "1024"
  backup-solution:logDetectorTimeout: "300"
  backup-solution:logDownloaderMemory: "1024"
  backup-solution:logDownloaderTimeout: "300"
  backup-solution:sqsVisibilityTimeout: "300"
  backup-solution:lambdaBatchSize: "10"
  backup-solution:eventBridgeSchedule: "rate(15 minutes)"
  backup-solution:s3LogPrefix: "aurora-logs"
  backup-solution:publishLambdaVersions: "true"
  backup-solution:backupLogTypes: "audit,error,instance"
  backup-solution:dbScannerImageVersion: "v1.0.0"
  backup-solution:logDetectorImageVersion: "v1.0.0"
  backup-solution:logDownloaderImageVersion: "v1.0.0"