config:
  aws:skipCredentialsValidation: "true"
  aws:skipMetadataApiCheck: "false"
  aws:region: "ap-southeast-1"
  # Network configuration
  aurora-audit-log-backup-lab:availabilityZone1: "ap-southeast-1a"
  aurora-audit-log-backup-lab:availabilityZone2: "ap-southeast-1b"
  # Test environment configuration
  aurora-audit-log-backup-lab:ec2KeyPairName: "keypair-sandbox0-sin-mymac.pem"
  aurora-audit-log-backup-lab:ec2InstanceType: "t4g.2xlarge"
  aurora-audit-log-backup-lab:auroraInstanceType: "db.r7g.2xlarge"
  # Lambda configuration
  aurora-audit-log-backup-lab:dbScannerMemory: "128"
  aurora-audit-log-backup-lab:dbScannerTimeout: "300"
  aurora-audit-log-backup-lab:logDetectorMemory: "512"
  aurora-audit-log-backup-lab:logDetectorTimeout: "300"
  aurora-audit-log-backup-lab:logDownloaderMemory: "1024"
  aurora-audit-log-backup-lab:logDownloaderTimeout: "600"
  aurora-audit-log-backup-lab:eventBridgeSchedule: "rate(15 minutes)"
  aurora-audit-log-backup-lab:s3LogPrefix: "logs"
  aurora-audit-log-backup-lab:lambdaBatchSize: "10"
  aurora-audit-log-backup-lab:backupLogTypes: "audit"
  # Image versions
  aurora-audit-log-backup-lab:dbScannerImageVersion: "v1.0.0"
  aurora-audit-log-backup-lab:logDetectorImageVersion: "v1.0.0"
  aurora-audit-log-backup-lab:logDownloaderImageVersion: "v1.0.0"
  aurora-audit-log-backup-lab:publishLambdaVersions: "true"
  aurora-audit-log-backup-lab:customTags: '{"Application": "AuroraAuditLogBackup", "Environment": "Lab", "auto-delete": "no", "Team": "personal"}'
  aurora-audit-log-backup-lab:environment: dev
  aurora-audit-log-backup-lab:owner: cloud-engineering-team
  aurora-audit-log-backup-lab:project: aurora-audit-log-backup
